apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-diabetes-app
  labels:
    app: flask-diabetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-diabetes
  template:
    metadata:
      labels:
        app: flask-diabetes
    spec:
      containers:
      - name: flask-diabetes
        image: arunbits/test:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-diabetes-service
spec:
  type: LoadBalancer
  selector:
    app: flask-diabetes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
