name: Java Build and Test

on:
  push:
    branches:
      - main   # Trigger the pipeline when pushing to the main branch
  pull_request:
    branches:
      - main   # Trigger the pipeline on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version you need (e.g., 11, 8, etc.)
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean install  # Use Maven to clean and build the project

      - name: Run tests with Maven
        run: |
          mvn test  # Run tests using Maven
          
      - name: Build JAR
        run: |
          mvn package  # Package the project into a JAR file (optional step)
          
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-build-artifact
          path: target/*.jar  # Specify the path where the JAR file is created
