name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Lint the code using Checkstyle
      - name: Lint with Checkstyle
        run: |
          curl -O https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar
          java -jar checkstyle-8.45-all.jar -c /google_checks.xml src/**/*.java

      # Step 4: Compile the code and run tests
      - name: Compile and Test
        run: |
          javac HelloWorld.java
          java HelloWorld
          
      # Step 5: Deploy to S3 (Fixed)
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          folder: './'
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: 'us-east-1'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
