name: Java Build and Test

on:
  push:
    branches:
      - main   # Trigger the pipeline when pushing to the main branch
  pull_request:
    branches:
      - main   # Trigger the pipeline on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version you need (e.g., 11, 8, etc.)
          distribution: 'temurin'

      # Step 3: Lint the code using Checkstyle
      - name: Lint with Checkstyle
        run: |
          curl -O https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar
          java -jar checkstyle-8.45-all.jar -c /google_checks.xml src/**/*.java

      # Step 4: Compile the code and run tests
      - name: Compile and Test
        run: |
          javac HelloWorld.java
          java HelloWorld
          
      # Step 5: Deploy to S3 (Fixed)
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          folder: './'
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: 'us-east-1'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
